package org.qinlinj.algoframework._400_binary_tree_algo._420_binary_tree_algo_practice_I._424_problem_decomposition_thinking_practice_I;

public class _424_c_ConstructBinaryTreeFromPreorderPostorder {
}
